/**
 * Country list for the country pickers, carried over from the old
 * dashboard (admin/scripts/countries.js) so both send the same ISO alpha-2
 * codes to the API.
 */

export interface Country {
  code2: string
  code3: string
  name: string
}

export const COUNTRIES: readonly Country[] = [
  { code2: "AF", code3: "AFG", name: "Afghanistan" },
  { code2: "AL", code3: "ALB", name: "Albania" },
  { code2: "DZ", code3: "DZA", name: "Algeria" },
  { code2: "AD", code3: "AND", name: "Andorra" },
  { code2: "AO", code3: "AGO", name: "Angola" },
  { code2: "AI", code3: "AIA", name: "Anguilla" },
  { code2: "AR", code3: "ARG", name: "Argentina" },
  { code2: "AM", code3: "ARM", name: "Armenia" },
  { code2: "AU", code3: "AUS", name: "Australia" },
  { code2: "AT", code3: "AUT", name: "Austria" },
  { code2: "AZ", code3: "AZE", name: "Azerbaijan" },
  { code2: "BS", code3: "BHS", name: "Bahamas" },
  { code2: "BH", code3: "BHR", name: "Bahrain" },
  { code2: "BD", code3: "BGD", name: "Bangladesh" },
  { code2: "BY", code3: "BLR", name: "Belarus" },
  { code2: "BE", code3: "BEL", name: "Belgium" },
  { code2: "BZ", code3: "BLZ", name: "Belize" },
  { code2: "BJ", code3: "BEN", name: "Benin" },
  { code2: "BM", code3: "BMU", name: "Bermuda" },
  { code2: "BT", code3: "BTN", name: "Bhutan" },
  { code2: "BA", code3: "BIH", name: "Bosnia and Herzegovina" },
  { code2: "BW", code3: "BWA", name: "Botswana" },
  { code2: "BR", code3: "BRA", name: "Brazil" },
  { code2: "BN", code3: "BRN", name: "Brunei" },
  { code2: "BG", code3: "BGR", name: "Bulgaria" },
  { code2: "BF", code3: "BFA", name: "Burkina Faso" },
  { code2: "BI", code3: "BDI", name: "Burundi" },
  { code2: "KH", code3: "KHM", name: "Cambodia" },
  { code2: "CM", code3: "CMR", name: "Cameroon" },
  { code2: "CA", code3: "CAN", name: "Canada" },
  { code2: "CV", code3: "CPV", name: "Cape Verde" },
  { code2: "CF", code3: "CAF", name: "Central African Republic" },
  { code2: "TD", code3: "TCD", name: "Chad" },
  { code2: "CL", code3: "CHL", name: "Chile" },
  { code2: "CN", code3: "CHN", name: "China" },
  { code2: "CO", code3: "COL", name: "Colombia" },
  { code2: "KM", code3: "COM", name: "Comoros" },
  { code2: "CR", code3: "CRI", name: "Costa Rica" },
  { code2: "CI", code3: "CIV", name: "Côte d'Ivoire" },
  { code2: "HR", code3: "HRV", name: "Croatia" },
  { code2: "CU", code3: "CUB", name: "Cuba" },
  { code2: "CY", code3: "CYP", name: "Cyprus" },
  { code2: "CZ", code3: "CZE", name: "Czechia" },
  { code2: "DK", code3: "DNK", name: "Denmark" },
  { code2: "DJ", code3: "DJI", name: "Djibouti" },
  { code2: "DM", code3: "DMA", name: "Dominica" },
  { code2: "DO", code3: "DOM", name: "Dominican Republic" },
  { code2: "CD", code3: "COD", name: "DR Congo" },
  { code2: "EC", code3: "ECU", name: "Ecuador" },
  { code2: "EG", code3: "EGY", name: "Egypt" },
  { code2: "SV", code3: "SLV", name: "El Salvador" },
  { code2: "GQ", code3: "GNQ", name: "Equatorial Guinea" },
  { code2: "ER", code3: "ERI", name: "Eritrea" },
  { code2: "EE", code3: "EST", name: "Estonia" },
  { code2: "ET", code3: "ETH", name: "Ethiopia" },
  { code2: "FO", code3: "FRO", name: "Faroe Islands" },
  { code2: "FI", code3: "FIN", name: "Finland" },
  { code2: "FR", code3: "FRA", name: "France" },
  { code2: "GA", code3: "GAB", name: "Gabon" },
  { code2: "GM", code3: "GMB", name: "Gambia" },
  { code2: "GE", code3: "GEO", name: "Georgia" },
  { code2: "DE", code3: "DEU", name: "Germany" },
  { code2: "GH", code3: "GHA", name: "Ghana" },
  { code2: "GI", code3: "GIB", name: "Gibraltar" },
  { code2: "GR", code3: "GRC", name: "Greece" },
  { code2: "GL", code3: "GRL", name: "Greenland" },
  { code2: "GD", code3: "GRD", name: "Grenada" },
  { code2: "GT", code3: "GTM", name: "Guatemala" },
  { code2: "GN", code3: "GIN", name: "Guinea" },
  { code2: "GW", code3: "GNB", name: "Guinea-Bissau" },
  { code2: "GY", code3: "GUY", name: "Guyana" },
  { code2: "HT", code3: "HTI", name: "Haiti" },
  { code2: "HN", code3: "HND", name: "Honduras" },
  { code2: "HK", code3: "HKG", name: "Hong Kong" },
  { code2: "HU", code3: "HUN", name: "Hungary" },
  { code2: "IS", code3: "ISL", name: "Iceland" },
  { code2: "IN", code3: "IND", name: "India" },
  { code2: "ID", code3: "IDN", name: "Indonesia" },
  { code2: "IR", code3: "IRN", name: "Iran" },
  { code2: "IQ", code3: "IRQ", name: "Iraq" },
  { code2: "IE", code3: "IRL", name: "Ireland" },
  { code2: "IL", code3: "ISR", name: "Israel" },
  { code2: "IT", code3: "ITA", name: "Italy" },
  { code2: "JM", code3: "JAM", name: "Jamaica" },
  { code2: "JP", code3: "JPN", name: "Japan" },
  { code2: "JO", code3: "JOR", name: "Jordan" },
  { code2: "KZ", code3: "KAZ", name: "Kazakhstan" },
  { code2: "KE", code3: "KEN", name: "Kenya" },
  { code2: "XK", code3: "XKX", name: "Kosovo" },
  { code2: "KW", code3: "KWT", name: "Kuwait" },
  { code2: "KG", code3: "KGZ", name: "Kyrgyzstan" },
  { code2: "LA", code3: "LAO", name: "Laos" },
  { code2: "LV", code3: "LVA", name: "Latvia" },
  { code2: "LB", code3: "LBN", name: "Lebanon" },
  { code2: "LS", code3: "LSO", name: "Lesotho" },
  { code2: "LR", code3: "LBR", name: "Liberia" },
  { code2: "LY", code3: "LBY", name: "Libya" },
  { code2: "LI", code3: "LIE", name: "Liechtenstein" },
  { code2: "LT", code3: "LTU", name: "Lithuania" },
  { code2: "LU", code3: "LUX", name: "Luxembourg" },
  { code2: "MO", code3: "MAC", name: "Macao" },
  { code2: "MG", code3: "MDG", name: "Madagascar" },
  { code2: "MW", code3: "MWI", name: "Malawi" },
  { code2: "MY", code3: "MYS", name: "Malaysia" },
  { code2: "MV", code3: "MDV", name: "Maldives" },
  { code2: "ML", code3: "MLI", name: "Mali" },
  { code2: "MT", code3: "MLT", name: "Malta" },
  { code2: "MR", code3: "MRT", name: "Mauritania" },
  { code2: "MU", code3: "MUS", name: "Mauritius" },
  { code2: "MX", code3: "MEX", name: "Mexico" },
  { code2: "MD", code3: "MDA", name: "Moldova" },
  { code2: "MC", code3: "MCO", name: "Monaco" },
  { code2: "MN", code3: "MNG", name: "Mongolia" },
  { code2: "ME", code3: "MNE", name: "Montenegro" },
  { code2: "MA", code3: "MAR", name: "Morocco" },
  { code2: "MZ", code3: "MOZ", name: "Mozambique" },
  { code2: "NA", code3: "NAM", name: "Namibia" },
  { code2: "NP", code3: "NPL", name: "Nepal" },
  { code2: "NL", code3: "NLD", name: "Netherlands" },
  { code2: "NZ", code3: "NZL", name: "New Zealand" },
  { code2: "NI", code3: "NIC", name: "Nicaragua" },
  { code2: "NG", code3: "NGA", name: "Nigeria" },
  { code2: "MK", code3: "MKD", name: "North Macedonia" },
  { code2: "NO", code3: "NOR", name: "Norway" },
  { code2: "OM", code3: "OMN", name: "Oman" },
  { code2: "PK", code3: "PAK", name: "Pakistan" },
  { code2: "PA", code3: "PAN", name: "Panama" },
  { code2: "PY", code3: "PRY", name: "Paraguay" },
  { code2: "PE", code3: "PER", name: "Peru" },
  { code2: "PH", code3: "PHL", name: "Philippines" },
  { code2: "PL", code3: "POL", name: "Poland" },
  { code2: "PT", code3: "PRT", name: "Portugal" },
  { code2: "QA", code3: "QAT", name: "Qatar" },
  { code2: "CG", code3: "COG", name: "Republic of the Congo" },
  { code2: "RO", code3: "ROU", name: "Romania" },
  { code2: "RU", code3: "RUS", name: "Russian Federation" },
  { code2: "RW", code3: "RWA", name: "Rwanda" },
  { code2: "SM", code3: "SMR", name: "San Marino" },
  { code2: "SA", code3: "SAU", name: "Saudi Arabia" },
  { code2: "SN", code3: "SEN", name: "Senegal" },
  { code2: "RS", code3: "SRB", name: "Serbia" },
  { code2: "SL", code3: "SLE", name: "Sierra Leone" },
  { code2: "SG", code3: "SGP", name: "Singapore" },
  { code2: "SK", code3: "SVK", name: "Slovakia" },
  { code2: "SI", code3: "SVN", name: "Slovenia" },
  { code2: "SO", code3: "SOM", name: "Somalia" },
  { code2: "ZA", code3: "ZAF", name: "South Africa" },
  { code2: "KR", code3: "KOR", name: "South Korea" },
  { code2: "SS", code3: "SSD", name: "South Sudan" },
  { code2: "ES", code3: "ESP", name: "Spain" },
  { code2: "LK", code3: "LKA", name: "Sri Lanka" },
  { code2: "SD", code3: "SDN", name: "Sudan" },
  { code2: "SE", code3: "SWE", name: "Sweden" },
  { code2: "CH", code3: "CHE", name: "Switzerland" },
  { code2: "SY", code3: "SYR", name: "Syria" },
  { code2: "TW", code3: "TWN", name: "Taiwan" },
  { code2: "TZ", code3: "TZA", name: "Tanzania" },
  { code2: "TH", code3: "THA", name: "Thailand" },
  { code2: "TL", code3: "TLS", name: "Timor-Leste" },
  { code2: "TG", code3: "TGO", name: "Togo" },
  { code2: "TN", code3: "TUN", name: "Tunisia" },
  { code2: "TR", code3: "TUR", name: "Türkiye" },
  { code2: "TM", code3: "TKM", name: "Turkmenistan" },
  { code2: "UG", code3: "UGA", name: "Uganda" },
  { code2: "UA", code3: "UKR", name: "Ukraine" },
  { code2: "AE", code3: "ARE", name: "United Arab Emirates" },
  { code2: "GB", code3: "GBR", name: "United Kingdom" },
  { code2: "US", code3: "USA", name: "United States" },
  { code2: "UY", code3: "URY", name: "Uruguay" },
  { code2: "UZ", code3: "UZB", name: "Uzbekistan" },
  { code2: "VE", code3: "VEN", name: "Venezuela" },
  { code2: "VN", code3: "VNM", name: "Viet Nam" },
  { code2: "YE", code3: "YEM", name: "Yemen" },
  { code2: "ZM", code3: "ZMB", name: "Zambia" },
  { code2: "ZW", code3: "ZWE", name: "Zimbabwe" },
]

/** The Unicode flag: two regional-indicator letters (drawn by the vendored flag font on Windows). */
export function countryFlag(code2: string | null | undefined): string {
  if (!code2 || !/^[A-Za-z]{2}$/.test(code2)) return ""
  return String.fromCodePoint(...[...code2.toUpperCase()].map((c) => 0x1f1a5 + c.charCodeAt(0)))
}

export function countryByCode(code: string | null | undefined): Country | undefined {
  if (!code) return undefined
  const upper = code.toUpperCase()
  return COUNTRIES.find((c) => c.code2 === upper || c.code3 === upper)
}

/** "🇳🇬 Nigeria" for a known code, the code itself otherwise. */
export function countryLabel(code: string | null | undefined): string | null {
  if (!code) return null
  const country = countryByCode(code)
  return country ? `${countryFlag(country.code2)} ${country.name}` : code.toUpperCase()
}

export function searchCountries(query: string, limit = 50): Country[] {
  const q = query.trim().toLowerCase()
  if (!q) return COUNTRIES.slice(0, limit)
  return COUNTRIES.filter(
    (c) => c.name.toLowerCase().includes(q) || c.code2.toLowerCase() === q || c.code3.toLowerCase().includes(q),
  ).slice(0, limit)
}
