'use client'

import { Icons, StatusBadge } from '@/components/ui'
import { InfoGrid, InfoItem, Notice, Section } from '@/components/admin/kit'
import type { ForensicsResult } from '@/lib/types'

/** EXIF + error level analysis of a document image, from the server's forensics step. */
export function ForensicsView({ fr, full = true }: { fr: ForensicsResult; full?: boolean }) {
  const tone = fr.verdict === 'clean' ? 'success' : fr.verdict === 'suspicious' ? 'warning' : 'muted'
  const yes = (v: boolean | undefined) => (v ? 'Yes' : 'No')
  return (
    <div className="space-y-6">
      <Section title="Verdict" action={<StatusBadge tone={tone}>{(fr.verdict || 'unavailable').toUpperCase()}</StatusBadge>}>
        {fr.error ? <Notice tone="warning">{fr.error}</Notice> : <p className="text-sm text-neutral-400">EXIF metadata and error level analysis of the document image.</p>}
      </Section>
      <Section title="EXIF metadata">
        <InfoGrid>
          <InfoItem label="EXIF present">{yes(fr.exif_present)}</InfoItem>
          <InfoItem label="Camera make">{fr.camera_make || '—'}</InfoItem>
          <InfoItem label="Camera model">{fr.camera_model || '—'}</InfoItem>
          {full ? <InfoItem label="Captured at">{fr.datetime_original || '—'}</InfoItem> : null}
          <InfoItem label="Software tag">{fr.software_tag || '—'}</InfoItem>
          {full ? <InfoItem label="GPS present">{yes(fr.gps_present)}</InfoItem> : null}
        </InfoGrid>
      </Section>
      <Section title="Error level analysis">
        <div className="space-y-4">
          <InfoGrid>
            <InfoItem label="ELA score">{fr.ela_score ?? '—'}</InfoItem>
            <InfoItem label="Editing software detected">{yes(fr.editing_software_detected)}</InfoItem>
            {full ? <InfoItem label="Possible resave">{fr.resave_detected ? 'Yes (low confidence)' : 'No'}</InfoItem> : null}
          </InfoGrid>
          {fr.ela_heatmap_b64 ? (
            // A data: URI generated by the server's forensics step.
            // eslint-disable-next-line @next/next/no-img-element
            <img src={fr.ela_heatmap_b64} alt="ELA heatmap" className="max-w-full rounded-xl border border-neutral-800" />
          ) : null}
        </div>
      </Section>
      {fr.risk_flags?.length ? (
        <Section title="Risk flags">
          <ul className="space-y-2">
            {fr.risk_flags.map((flag) => (
              <li key={flag} className="flex items-start gap-2 text-sm text-amber-300">
                <Icons.AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                {flag}
              </li>
            ))}
          </ul>
        </Section>
      ) : null}
    </div>
  )
}
