// Loaded as a plain <script> tag — no module imports needed.
// Sets window.COUNTRIES and window.countryFlag for id.js to use.

window.COUNTRIES = [
  { code3: 'AFG', code2: 'AF', name: 'Afghanistan' },
  { code3: 'AGO', code2: 'AO', name: 'Angola' },
  { code3: 'AIA', code2: 'AI', name: 'Anguilla' },
  { code3: 'ALB', code2: 'AL', name: 'Albania' },
  { code3: 'AND', code2: 'AD', name: 'Andorra' },
  { code3: 'ARE', code2: 'AE', name: 'United Arab Emirates' },
  { code3: 'ARG', code2: 'AR', name: 'Argentina' },
  { code3: 'ARM', code2: 'AM', name: 'Armenia' },
  { code3: 'AUS', code2: 'AU', name: 'Australia' },
  { code3: 'AUT', code2: 'AT', name: 'Austria' },
  { code3: 'AZE', code2: 'AZ', name: 'Azerbaijan' },
  { code3: 'BDI', code2: 'BI', name: 'Burundi' },
  { code3: 'BEL', code2: 'BE', name: 'Belgium' },
  { code3: 'BEN', code2: 'BJ', name: 'Benin' },
  { code3: 'BFA', code2: 'BF', name: 'Burkina Faso' },
  { code3: 'BGD', code2: 'BD', name: 'Bangladesh' },
  { code3: 'BGR', code2: 'BG', name: 'Bulgaria' },
  { code3: 'BHR', code2: 'BH', name: 'Bahrain' },
  { code3: 'BHS', code2: 'BS', name: 'Bahamas' },
  { code3: 'BIH', code2: 'BA', name: 'Bosnia and Herzegovina' },
  { code3: 'BLR', code2: 'BY', name: 'Belarus' },
  { code3: 'BLZ', code2: 'BZ', name: 'Belize' },
  { code3: 'BMU', code2: 'BM', name: 'Bermuda' },
  { code3: 'BRA', code2: 'BR', name: 'Brazil' },
  { code3: 'BRN', code2: 'BN', name: 'Brunei' },
  { code3: 'BTN', code2: 'BT', name: 'Bhutan' },
  { code3: 'BWA', code2: 'BW', name: 'Botswana' },
  { code3: 'CAF', code2: 'CF', name: 'Central African Republic' },
  { code3: 'CAN', code2: 'CA', name: 'Canada' },
  { code3: 'CHE', code2: 'CH', name: 'Switzerland' },
  { code3: 'CHL', code2: 'CL', name: 'Chile' },
  { code3: 'CHN', code2: 'CN', name: 'China' },
  { code3: 'CIV', code2: 'CI', name: "Côte d'Ivoire" },
  { code3: 'CMR', code2: 'CM', name: 'Cameroon' },
  { code3: 'COD', code2: 'CD', name: 'DR Congo' },
  { code3: 'COG', code2: 'CG', name: 'Republic of the Congo' },
  { code3: 'COL', code2: 'CO', name: 'Colombia' },
  { code3: 'COM', code2: 'KM', name: 'Comoros' },
  { code3: 'CPV', code2: 'CV', name: 'Cape Verde' },
  { code3: 'CRI', code2: 'CR', name: 'Costa Rica' },
  { code3: 'CUB', code2: 'CU', name: 'Cuba' },
  { code3: 'CYP', code2: 'CY', name: 'Cyprus' },
  { code3: 'CZE', code2: 'CZ', name: 'Czechia' },
  { code3: 'DEU', code2: 'DE', name: 'Germany' },
  { code3: 'DJI', code2: 'DJ', name: 'Djibouti' },
  { code3: 'DMA', code2: 'DM', name: 'Dominica' },
  { code3: 'DNK', code2: 'DK', name: 'Denmark' },
  { code3: 'DOM', code2: 'DO', name: 'Dominican Republic' },
  { code3: 'DZA', code2: 'DZ', name: 'Algeria' },
  { code3: 'ECU', code2: 'EC', name: 'Ecuador' },
  { code3: 'EGY', code2: 'EG', name: 'Egypt' },
  { code3: 'ERI', code2: 'ER', name: 'Eritrea' },
  { code3: 'ESP', code2: 'ES', name: 'Spain' },
  { code3: 'EST', code2: 'EE', name: 'Estonia' },
  { code3: 'ETH', code2: 'ET', name: 'Ethiopia' },
  { code3: 'FIN', code2: 'FI', name: 'Finland' },
  { code3: 'FRA', code2: 'FR', name: 'France' },
  { code3: 'FRO', code2: 'FO', name: 'Faroe Islands' },
  { code3: 'GAB', code2: 'GA', name: 'Gabon' },
  { code3: 'GBR', code2: 'GB', name: 'United Kingdom' },
  { code3: 'GEO', code2: 'GE', name: 'Georgia' },
  { code3: 'GHA', code2: 'GH', name: 'Ghana' },
  { code3: 'GIB', code2: 'GI', name: 'Gibraltar' },
  { code3: 'GIN', code2: 'GN', name: 'Guinea' },
  { code3: 'GMB', code2: 'GM', name: 'Gambia' },
  { code3: 'GNB', code2: 'GW', name: 'Guinea-Bissau' },
  { code3: 'GNQ', code2: 'GQ', name: 'Equatorial Guinea' },
  { code3: 'GRC', code2: 'GR', name: 'Greece' },
  { code3: 'GRD', code2: 'GD', name: 'Grenada' },
  { code3: 'GRL', code2: 'GL', name: 'Greenland' },
  { code3: 'GTM', code2: 'GT', name: 'Guatemala' },
  { code3: 'GUY', code2: 'GY', name: 'Guyana' },
  { code3: 'HKG', code2: 'HK', name: 'Hong Kong' },
  { code3: 'HND', code2: 'HN', name: 'Honduras' },
  { code3: 'HRV', code2: 'HR', name: 'Croatia' },
  { code3: 'HTI', code2: 'HT', name: 'Haiti' },
  { code3: 'HUN', code2: 'HU', name: 'Hungary' },
  { code3: 'IDN', code2: 'ID', name: 'Indonesia' },
  { code3: 'IND', code2: 'IN', name: 'India' },
  { code3: 'IRL', code2: 'IE', name: 'Ireland' },
  { code3: 'IRN', code2: 'IR', name: 'Iran' },
  { code3: 'IRQ', code2: 'IQ', name: 'Iraq' },
  { code3: 'ISL', code2: 'IS', name: 'Iceland' },
  { code3: 'ISR', code2: 'IL', name: 'Israel' },
  { code3: 'ITA', code2: 'IT', name: 'Italy' },
  { code3: 'JAM', code2: 'JM', name: 'Jamaica' },
  { code3: 'JOR', code2: 'JO', name: 'Jordan' },
  { code3: 'JPN', code2: 'JP', name: 'Japan' },
  { code3: 'KAZ', code2: 'KZ', name: 'Kazakhstan' },
  { code3: 'KEN', code2: 'KE', name: 'Kenya' },
  { code3: 'KGZ', code2: 'KG', name: 'Kyrgyzstan' },
  { code3: 'KHM', code2: 'KH', name: 'Cambodia' },
  { code3: 'KOR', code2: 'KR', name: 'South Korea' },
  { code3: 'KWT', code2: 'KW', name: 'Kuwait' },
  { code3: 'LAO', code2: 'LA', name: 'Laos' },
  { code3: 'LBN', code2: 'LB', name: 'Lebanon' },
  { code3: 'LBR', code2: 'LR', name: 'Liberia' },
  { code3: 'LBY', code2: 'LY', name: 'Libya' },
  { code3: 'LIE', code2: 'LI', name: 'Liechtenstein' },
  { code3: 'LKA', code2: 'LK', name: 'Sri Lanka' },
  { code3: 'LSO', code2: 'LS', name: 'Lesotho' },
  { code3: 'LTU', code2: 'LT', name: 'Lithuania' },
  { code3: 'LUX', code2: 'LU', name: 'Luxembourg' },
  { code3: 'LVA', code2: 'LV', name: 'Latvia' },
  { code3: 'MAC', code2: 'MO', name: 'Macao' },
  { code3: 'MAR', code2: 'MA', name: 'Morocco' },
  { code3: 'MCO', code2: 'MC', name: 'Monaco' },
  { code3: 'MDA', code2: 'MD', name: 'Moldova' },
  { code3: 'MDG', code2: 'MG', name: 'Madagascar' },
  { code3: 'MDV', code2: 'MV', name: 'Maldives' },
  { code3: 'MEX', code2: 'MX', name: 'Mexico' },
  { code3: 'MKD', code2: 'MK', name: 'North Macedonia' },
  { code3: 'MLI', code2: 'ML', name: 'Mali' },
  { code3: 'MLT', code2: 'MT', name: 'Malta' },
  { code3: 'MNE', code2: 'ME', name: 'Montenegro' },
  { code3: 'MNG', code2: 'MN', name: 'Mongolia' },
  { code3: 'MOZ', code2: 'MZ', name: 'Mozambique' },
  { code3: 'MRT', code2: 'MR', name: 'Mauritania' },
  { code3: 'MUS', code2: 'MU', name: 'Mauritius' },
  { code3: 'MWI', code2: 'MW', name: 'Malawi' },
  { code3: 'MYS', code2: 'MY', name: 'Malaysia' },
  { code3: 'NAM', code2: 'NA', name: 'Namibia' },
  { code3: 'NGA', code2: 'NG', name: 'Nigeria' },
  { code3: 'NIC', code2: 'NI', name: 'Nicaragua' },
  { code3: 'NLD', code2: 'NL', name: 'Netherlands' },
  { code3: 'NOR', code2: 'NO', name: 'Norway' },
  { code3: 'NPL', code2: 'NP', name: 'Nepal' },
  { code3: 'NZL', code2: 'NZ', name: 'New Zealand' },
  { code3: 'OMN', code2: 'OM', name: 'Oman' },
  { code3: 'PAK', code2: 'PK', name: 'Pakistan' },
  { code3: 'PAN', code2: 'PA', name: 'Panama' },
  { code3: 'PER', code2: 'PE', name: 'Peru' },
  { code3: 'PHL', code2: 'PH', name: 'Philippines' },
  { code3: 'POL', code2: 'PL', name: 'Poland' },
  { code3: 'PRT', code2: 'PT', name: 'Portugal' },
  { code3: 'PRY', code2: 'PY', name: 'Paraguay' },
  { code3: 'QAT', code2: 'QA', name: 'Qatar' },
  { code3: 'ROU', code2: 'RO', name: 'Romania' },
  { code3: 'RUS', code2: 'RU', name: 'Russian Federation' },
  { code3: 'RWA', code2: 'RW', name: 'Rwanda' },
  { code3: 'SAU', code2: 'SA', name: 'Saudi Arabia' },
  { code3: 'SDN', code2: 'SD', name: 'Sudan' },
  { code3: 'SEN', code2: 'SN', name: 'Senegal' },
  { code3: 'SGP', code2: 'SG', name: 'Singapore' },
  { code3: 'SLE', code2: 'SL', name: 'Sierra Leone' },
  { code3: 'SLV', code2: 'SV', name: 'El Salvador' },
  { code3: 'SMR', code2: 'SM', name: 'San Marino' },
  { code3: 'SOM', code2: 'SO', name: 'Somalia' },
  { code3: 'SRB', code2: 'RS', name: 'Serbia' },
  { code3: 'SSD', code2: 'SS', name: 'South Sudan' },
  { code3: 'SVK', code2: 'SK', name: 'Slovakia' },
  { code3: 'SVN', code2: 'SI', name: 'Slovenia' },
  { code3: 'SWE', code2: 'SE', name: 'Sweden' },
  { code3: 'SYR', code2: 'SY', name: 'Syria' },
  { code3: 'TCD', code2: 'TD', name: 'Chad' },
  { code3: 'TGO', code2: 'TG', name: 'Togo' },
  { code3: 'THA', code2: 'TH', name: 'Thailand' },
  { code3: 'TKM', code2: 'TM', name: 'Turkmenistan' },
  { code3: 'TLS', code2: 'TL', name: 'Timor-Leste' },
  { code3: 'TUN', code2: 'TN', name: 'Tunisia' },
  { code3: 'TUR', code2: 'TR', name: 'Türkiye' },
  { code3: 'TWN', code2: 'TW', name: 'Taiwan' },
  { code3: 'TZA', code2: 'TZ', name: 'Tanzania' },
  { code3: 'UGA', code2: 'UG', name: 'Uganda' },
  { code3: 'UKR', code2: 'UA', name: 'Ukraine' },
  { code3: 'URY', code2: 'UY', name: 'Uruguay' },
  { code3: 'USA', code2: 'US', name: 'United States' },
  { code3: 'UZB', code2: 'UZ', name: 'Uzbekistan' },
  { code3: 'VEN', code2: 'VE', name: 'Venezuela' },
  { code3: 'VNM', code2: 'VN', name: 'Viet Nam' },
  { code3: 'XKX', code2: 'XK', name: 'Kosovo' },
  { code3: 'YEM', code2: 'YE', name: 'Yemen' },
  { code3: 'ZAF', code2: 'ZA', name: 'South Africa' },
  { code3: 'ZMB', code2: 'ZM', name: 'Zambia' },
  { code3: 'ZWE', code2: 'ZW', name: 'Zimbabwe' },
].sort((a, b) => a.name.localeCompare(b.name));

window.countryFlag = function (code2) {
  if (!code2 || code2.length < 2) return '';
  return Array.from(code2.toUpperCase()).map(
    c => String.fromCodePoint(0x1F1E6 - 65 + c.charCodeAt(0))
  ).join('');
};
